# to execute docker file use the command docker-compose up
# if file name is different docker-compase -f filename.yaml
# add the '-d' flag for execution in background without showing you logs
# shm is shared memory, given to avoid browser cache inside conatiner

version: "3"
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: sel-hub
    restart: always
    ports:
      - "4445:4444"

  chrome:
    image: selenium/node-chrome-debug:latest
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    restart: on-failure:3

  chrome_79:
    image: selenium/node-chrome-debug:3.141.59-zinc
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    restart: on-failure:3
  firefox:
    image: selenium/node-firefox-debug:latest
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    restart: on-failure:3